const fs = require('fs');
const {
  LANGUAGES,
  LANGUAGES_MD,
  LANGUAGES_JS
} = require('./common');

fs.writeFileSync(
  LANGUAGES_MD,
  [
    '<!-- Generated by scripts/generate-files.js -- DO NOT EDIT BY HAND -->',
    'If you do not see your language here, open an issue: https://github.com/TurboWarp/translations/issues/new',
    '',
    '| Language | File |',
    '| :-: | :-: |',
    ...Array.from(Object.entries(LANGUAGES))
      .map(([code, {name}]) => `| ${name} | ${code}.yaml |`)
  ].join('\n')
);

fs.writeFileSync(
  LANGUAGES_JS,
  [
    '// Generated by scripts/generate-files.js -- DO NOT EDIT BY HAND',
    'module.exports = {',
    ...Array.from(Object.entries(LANGUAGES))
      .map(([code]) => `  '${code}': require('./languages/${code}.json'),`),
    '};',
    ''
  ].join('\n')
);
